// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import FileFormController from "./file_form_controller"
application.register("file-form", FileFormController)

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import MultiSelectController from "./multi_select_controller"
application.register("multi-select", MultiSelectController)

import SearchFormController from "./search_form_controller"
application.register("search-form", SearchFormController)
